In [1]:
import torch

In [7]:
ckpt = torch.load("/home/icmore_acc/Downloads/pyvision_dev/pytorch_vision/dinov3_vits16_pretrain_lvd1689m-08c60483.pth", weights_only=False)
ckpt_st = torch.load("/home/icmore_acc/Downloads/pyvision_dev/pytorch_vision/dinov3_privatedata_student.pth", weights_only=False)
ckpt_te = torch.load("/home/icmore_acc/Downloads/pyvision_dev/pytorch_vision/dinov3_privatedata_teacher.pth", weights_only=False)

In [9]:
d1 = {k:v.shape for k, v in ckpt.items()}
d2 = {k:v.shape for k, v in ckpt_st.items()}
d3 = {k:v.shape for k, v in ckpt_te.items()}

In [19]:
import pandas as pd

df = pd.DataFrame([d1, d2, d3])
df = df.T
df.columns = ["master", "student", "teacher"]

                                    master           student           teacher
cls_token                      (1, 1, 384)       (1, 1, 384)       (1, 1, 384)
storage_tokens                 (1, 4, 384)       (1, 4, 384)       (1, 4, 384)
mask_token                        (1, 384)          (1, 384)          (1, 384)
patch_embed.proj.weight   (384, 3, 16, 16)  (384, 3, 16, 16)  (384, 3, 16, 16)
patch_embed.proj.bias               (384,)            (384,)            (384,)
...                                    ...               ...               ...
blocks.5.ls2.gamma                  (384,)            (384,)            (384,)
blocks.6.norm1.weight               (384,)            (384,)            (384,)
blocks.6.norm1.bias                 (384,)            (384,)            (384,)
blocks.6.attn.qkv.weight       (1152, 384)       (1152, 384)       (1152, 384)
blocks.6.attn.qkv.bias             (1152,)               NaN               NaN

[100 rows x 3 columns]

In [20]:
pd.set_option('display.max_rows', None)
df

,master,student,teacher
cls_token,"(1, 1, 384)","(1, 1, 384)","(1, 1, 384)"
storage_tokens,"(1, 4, 384)","(1, 4, 384)","(1, 4, 384)"
mask_token,"(1, 384)","(1, 384)","(1, 384)"
patch_embed.proj.weight,"(384, 3, 16, 16)","(384, 3, 16, 16)","(384, 3, 16, 16)"
patch_embed.proj.bias,"(384,)","(384,)","(384,)"
rope_embed.periods,"(16,)","(16,)","(16,)"
blocks.0.norm1.weight,"(384,)","(384,)","(384,)"
blocks.0.norm1.bias,"(384,)","(384,)","(384,)"
blocks.0.attn.qkv.weight,"(1152, 384)","(1152, 384)","(1152, 384)"
blocks.0.attn.qkv.bias,"(1152,)",NaN,NaN
blocks.0.attn.qkv.bias_mask,"(1152,)",NaN,NaN
blocks.0.attn.proj.weight,"(384, 384)","(384, 384)","(384, 384)"
blocks.0.attn.proj.bias,"(384,)","(384,)","(384,)"
blocks.0.ls1.gamma,"(384,)","(384,)","(384,)"
blocks.0.norm2.weight,"(384,)","(384,)","(384,)"
blocks.0.norm2.bias,"(384,)","(384,)","(384,)"
blocks.0.mlp.fc1.weight,"(1536, 384)",NaN,NaN
blocks.0.mlp.fc1.bias,"(1536,)",NaN,NaN
blocks.0.mlp.fc2.weight,"(384, 1536)",NaN,NaN
blocks.0.mlp.fc2.bias,"(384,)",NaN,NaN
blocks.0.ls2.gamma,"(384,)","(384,)","(384,)"
blocks.1.norm1.weight,"(384,)","(384,)","(384,)"
blocks.1.norm1.bias,"(384,)","(384,)","(384,)"
blocks.1.attn.qkv.weight,"(1152, 384)","(1152, 384)","(1152, 384)"
blocks.1.attn.qkv.bias,"(1152,)",NaN,NaN
blocks.1.attn.qkv.bias_mask,"(1152,)",NaN,NaN
blocks.1.attn.proj.weight,"(384, 384)","(384, 384)","(384, 384)"
blocks.1.attn.proj.bias,"(384,)","(384,)","(384,)"
blocks.1.ls1.gamma,"(384,)","(384,)","(384,)"
blocks.1.norm2.weight,"(384,)","(384,)","(384,)"
blocks.1.norm2.bias,"(384,)","(384,)","(384,)"
blocks.1.mlp.fc1.weight,"(1536, 384)",NaN,NaN
blocks.1.mlp.fc1.bias,"(1536,)",NaN,NaN
blocks.1.mlp.fc2.weight,"(384, 1536)",NaN,NaN
blocks.1.mlp.fc2.bias,"(384,)",NaN,NaN
blocks.1.ls2.gamma,"(384,)","(384,)","(384,)"
blocks.2.norm1.weight,"(384,)","(384,)","(384,)"
blocks.2.norm1.bias,"(384,)","(384,)","(384,)"
blocks.2.attn.qkv.weight,"(1152, 384)","(1152, 384)","(1152, 384)"
blocks.2.attn.qkv.bias,"(1152,)",NaN,NaN
blocks.2.attn.qkv.bias_mask,"(1152,)",NaN,NaN
blocks.2.attn.proj.weight,"(384, 384)","(384, 384)","(384, 384)"
blocks.2.attn.proj.bias,"(384,)","(384,)","(384,)"
blocks.2.ls1.gamma,"(384,)","(384,)","(384,)"
blocks.2.norm2.weight,"(384,)","(384,)","(384,)"
blocks.2.norm2.bias,"(384,)","(384,)","(384,)"
blocks.2.mlp.fc1.weight,"(1536, 384)",NaN,NaN
blocks.2.mlp.fc1.bias,"(1536,)",NaN,NaN
blocks.2.mlp.fc2.weight,"(384, 1536)",NaN,NaN
blocks.2.mlp.fc2.bias,"(384,)",NaN,NaN
blocks.2.ls2.gamma,"(384,)","(384,)","(384,)"
blocks.3.norm1.weight,"(384,)","(384,)","(384,)"
blocks.3.norm1.bias,"(384,)","(384,)","(384,)"
blocks.3.attn.qkv.weight,"(1152, 384)","(1152, 384)","(1152, 384)"
blocks.3.attn.qkv.bias,"(1152,)",NaN,NaN
blocks.3.attn.qkv.bias_mask,"(1152,)",NaN,NaN
blocks.3.attn.proj.weight,"(384, 384)","(384, 384)","(384, 384)"
blocks.3.attn.proj.bias,"(384,)","(384,)","(384,)"
blocks.3.ls1.gamma,"(384,)","(384,)","(384,)"
blocks.3.norm2.weight,"(384,)","(384,)","(384,)"
blocks.3.norm2.bias,"(384,)","(384,)","(384,)"
blocks.3.mlp.fc1.weight,"(1536, 384)",NaN,NaN
blocks.3.mlp.fc1.bias,"(1536,)",NaN,NaN
blocks.3.mlp.fc2.weight,"(384, 1536)",NaN,NaN
blocks.3.mlp.fc2.bias,"(384,)",NaN,NaN
blocks.3.ls2.gamma,"(384,)","(384,)","(384,)"
blocks.4.norm1.weight,"(384,)","(384,)","(384,)"
blocks.4.norm1.bias,"(384,)","(384,)","(384,)"
blocks.4.attn.qkv.weight,"(1152, 384)","(1152, 384)","(1152, 384)"
blocks.4.attn.qkv.bias,"(1152,)",NaN,NaN
blocks.4.attn.qkv.bias_mask,"(1152,)",NaN,NaN
blocks.4.attn.proj.weight,"(384, 384)","(384, 384)","(384, 384)"
blocks.4.attn.proj.bias,"(384,)","(384,)","(384,)"
blocks.4.ls1.gamma,"(384,)","(384,)","(384,)"
blocks.4.norm2.weight,"(384,)","(384,)","(384,)"
blocks.4.norm2.bias,"(384,)","(384,)","(384,)"
blocks.4.mlp.fc1.weight,"(1536, 384)",NaN,NaN
blocks.4.mlp.fc1.bias,"(1536,)",NaN,NaN
blocks.4.mlp.fc2.weight,"(384, 1536)",NaN,NaN
blocks.4.mlp.fc2.bias,"(384,)",NaN,NaN
blocks.4.ls2.gamma,"(384,)","(384,)","(384,)"
blocks.5.norm1.weight,"(384,)","(384,)","(384,)"
blocks.5.norm1.bias,"(384,)","(384,)","(384,)"
blocks.5.attn.qkv.weight,"(1152, 384)","(1152, 384)","(1152, 384)"
blocks.5.attn.qkv.bias,"(1152,)",NaN,NaN
blocks.5.attn.qkv.bias_mask,"(1152,)",NaN,NaN
blocks.5.attn.proj.weight,"(384, 384)","(384, 384)","(384, 384)"
blocks.5.attn.proj.bias,"(384,)","(384,)","(384,)"
blocks.5.ls1.gamma,"(384,)","(384,)","(384,)"
blocks.5.norm2.weight,"(384,)","(384,)","(384,)"
blocks.5.norm2.bias,"(384,)","(384,)","(384,)"
blocks.5.mlp.fc1.weight,"(1536, 384)",NaN,NaN
blocks.5.mlp.fc1.bias,"(1536,)",NaN,NaN
blocks.5.mlp.fc2.weight,"(384, 1536)",NaN,NaN
blocks.5.mlp.fc2.bias,"(384,)",NaN,NaN
blocks.5.ls2.gamma,"(384,)","(384,)","(384,)"
blocks.6.norm1.weight,"(384,)","(384,)","(384,)"
blocks.6.norm1.bias,"(384,)","(384,)","(384,)"
blocks.6.attn.qkv.weight,"(1152, 384)","(1152, 384)","(1152, 384)"
blocks.6.attn.qkv.bias,"(1152,)",NaN,NaN
blocks.6.attn.qkv.bias_mask,"(1152,)",NaN,NaN
blocks.6.attn.proj.weight,"(384, 384)","(384, 384)","(384, 384)"
blocks.6.attn.proj.bias,"(384,)","(384,)","(384,)"
blocks.6.ls1.gamma,"(384,)","(384,)","(384,)"
blocks.6.norm2.weight,"(384,)","(384,)","(384,)"
blocks.6.norm2.bias,"(384,)","(384,)","(384,)"
blocks.6.mlp.fc1.weight,"(1536, 384)",NaN,NaN
blocks.6.mlp.fc1.bias,"(1536,)",NaN,NaN
blocks.6.mlp.fc2.weight,"(384, 1536)",NaN,NaN
blocks.6.mlp.fc2.bias,"(384,)",NaN,NaN
blocks.6.ls2.gamma,"(384,)","(384,)","(384,)"
blocks.7.norm1.weight,"(384,)","(384,)","(384,)"
blocks.7.norm1.bias,"(384,)","(384,)","(384,)"
blocks.7.attn.qkv.weight,"(1152, 384)","(1152, 384)","(1152, 384)"
blocks.7.attn.qkv.bias,"(1152,)",NaN,NaN
blocks.7.attn.qkv.bias_mask,"(1152,)",NaN,NaN
blocks.7.attn.proj.weight,"(384, 384)","(384, 384)","(384, 384)"
blocks.7.attn.proj.bias,"(384,)","(384,)","(384,)"
blocks.7.ls1.gamma,"(384,)","(384,)","(384,)"
blocks.7.norm2.weight,"(384,)","(384,)","(384,)"
blocks.7.norm2.bias,"(384,)","(384,)","(384,)"
blocks.7.mlp.fc1.weight,"(1536, 384)",NaN,NaN
blocks.7.mlp.fc1.bias,"(1536,)",NaN,NaN
blocks.7.mlp.fc2.weight,"(384, 1536)",NaN,NaN
blocks.7.mlp.fc2.bias,"(384,)",NaN,NaN
blocks.7.ls2.gamma,"(384,)","(384,)","(384,)"
blocks.8.norm1.weight,"(384,)","(384,)","(384,)"
blocks.8.norm1.bias,"(384,)","(384,)","(384,)"
blocks.8.attn.qkv.weight,"(1152, 384)","(1152, 384)","(1152, 384)"
blocks.8.attn.qkv.bias,"(1152,)",NaN,NaN
blocks.8.attn.qkv.bias_mask,"(1152,)",NaN,NaN
blocks.8.attn.proj.weight,"(384, 384)","(384, 384)","(384, 384)"
blocks.8.attn.proj.bias,"(384,)","(384,)","(384,)"
blocks.8.ls1.gamma,"(384,)","(384,)","(384,)"
blocks.8.norm2.weight,"(384,)","(384,)","(384,)"
blocks.8.norm2.bias,"(384,)","(384,)","(384,)"
blocks.8.mlp.fc1.weight,"(1536, 384)",NaN,NaN
blocks.8.mlp.fc1.bias,"(1536,)",NaN,NaN
blocks.8.mlp.fc2.weight,"(384, 1536)",NaN,NaN
blocks.8.mlp.fc2.bias,"(384,)",NaN,NaN
blocks.8.ls2.gamma,"(384,)","(384,)","(384,)"
blocks.9.norm1.weight,"(384,)","(384,)","(384,)"
blocks.9.norm1.bias,"(384,)","(384,)","(384,)"
blocks.9.attn.qkv.weight,"(1152, 384)","(1152, 384)","(1152, 384)"
blocks.9.attn.qkv.bias,"(1152,)",NaN,NaN
blocks.9.attn.qkv.bias_mask,"(1152,)",NaN,NaN
blocks.9.attn.proj.weight,"(384, 384)","(384, 384)","(384, 384)"
blocks.9.attn.proj.bias,"(384,)","(384,)","(384,)"
blocks.9.ls1.gamma,"(384,)","(384,)","(384,)"
blocks.9.norm2.weight,"(384,)","(384,)","(384,)"
blocks.9.norm2.bias,"(384,)","(384,)","(384,)"
blocks.9.mlp.fc1.weight,"(1536, 384)",NaN,NaN
blocks.9.mlp.fc1.bias,"(1536,)",NaN,NaN
blocks.9.mlp.fc2.weight,"(384, 1536)",NaN,NaN
blocks.9.mlp.fc2.bias,"(384,)",NaN,NaN
blocks.9.ls2.gamma,"(384,)","(384,)","(384,)"
blocks.10.norm1.weight,"(384,)","(384,)","(384,)"
blocks.10.norm1.bias,"(384,)","(384,)","(384,)"
blocks.10.attn.qkv.weight,"(1152, 384)","(1152, 384)","(1152, 384)"
blocks.10.attn.qkv.bias,"(1152,)",NaN,NaN
blocks.10.attn.qkv.bias_mask,"(1152,)",NaN,NaN
blocks.10.attn.proj.weight,"(384, 384)","(384, 384)","(384, 384)"
blocks.10.attn.proj.bias,"(384,)","(384,)","(384,)"
blocks.10.ls1.gamma,"(384,)","(384,)","(384,)"
blocks.10.norm2.weight,"(384,)","(384,)","(384,)"
blocks.10.norm2.bias,"(384,)","(384,)","(384,)"
blocks.10.mlp.fc1.weight,"(1536, 384)",NaN,NaN
blocks.10.mlp.fc1.bias,"(1536,)",NaN,NaN
blocks.10.mlp.fc2.weight,"(384, 1536)",NaN,NaN
blocks.10.mlp.fc2.bias,"(384,)",NaN,NaN
blocks.10.ls2.gamma,"(384,)","(384,)","(384,)"
blocks.11.norm1.weight,"(384,)","(384,)","(384,)"
blocks.11.norm1.bias,"(384,)","(384,)","(384,)"
blocks.11.attn.qkv.weight,"(1152, 384)","(1152, 384)","(1152, 384)"
blocks.11.attn.qkv.bias,"(1152,)",NaN,NaN
blocks.11.attn.qkv.bias_mask,"(1152,)",NaN,NaN
blocks.11.attn.proj.weight,"(384, 384)","(384, 384)","(384, 384)"
blocks.11.attn.proj.bias,"(384,)","(384,)","(384,)"
blocks.11.ls1.gamma,"(384,)","(384,)","(384,)"
blocks.11.norm2.weight,"(384,)","(384,)","(384,)"
blocks.11.norm2.bias,"(384,)","(384,)","(384,)"
blocks.11.mlp.fc1.weight,"(1536, 384)",NaN,NaN
blocks.11.mlp.fc1.bias,"(1536,)",NaN,NaN
blocks.11.mlp.fc2.weight,"(384, 1536)",NaN,NaN
blocks.11.mlp.fc2.bias,"(384,)",NaN,NaN
blocks.11.ls2.gamma,"(384,)","(384,)","(384,)"
norm.weight,"(384,)","(384,)","(384,)"
norm.bias,"(384,)","(384,)","(384,)"
blocks.0.mlp.w1.weight,NaN,"(1024, 384)","(1024, 384)"
blocks.0.mlp.w1.bias,NaN,"(1024,)","(1024,)"
blocks.0.mlp.w2.weight,NaN,"(1024, 384)","(1024, 384)"
blocks.0.mlp.w2.bias,NaN,"(1024,)","(1024,)"
blocks.0.mlp.w3.weight,NaN,"(384, 1024)","(384, 1024)"
blocks.0.mlp.w3.bias,NaN,"(384,)","(384,)"
blocks.1.mlp.w1.weight,NaN,"(1024, 384)","(1024, 384)"
blocks.1.mlp.w1.bias,NaN,"(1024,)","(1024,)"
blocks.1.mlp.w2.weight,NaN,"(1024, 384)","(1024, 384)"
blocks.1.mlp.w2.bias,NaN,"(1024,)","(1024,)"
blocks.1.mlp.w3.weight,NaN,"(384, 1024)","(384, 1024)"
blocks.1.mlp.w3.bias,NaN,"(384,)","(384,)"
blocks.2.mlp.w1.weight,NaN,"(1024, 384)","(1024, 384)"
blocks.2.mlp.w1.bias,NaN,"(1024,)","(1024,)"
blocks.2.mlp.w2.weight,NaN,"(1024, 384)","(1024, 384)"
blocks.2.mlp.w2.bias,NaN,"(1024,)","(1024,)"
blocks.2.mlp.w3.weight,NaN,"(384, 1024)","(384, 1024)"
blocks.2.mlp.w3.bias,NaN,"(384,)","(384,)"
blocks.3.mlp.w1.weight,NaN,"(1024, 384)","(1024, 384)"
blocks.3.mlp.w1.bias,NaN,"(1024,)","(1024,)"
blocks.3.mlp.w2.weight,NaN,"(1024, 384)","(1024, 384)"
blocks.3.mlp.w2.bias,NaN,"(1024,)","(1024,)"
blocks.3.mlp.w3.weight,NaN,"(384, 1024)","(384, 1024)"
blocks.3.mlp.w3.bias,NaN,"(384,)","(384,)"
blocks.4.mlp.w1.weight,NaN,"(1024, 384)","(1024, 384)"
blocks.4.mlp.w1.bias,NaN,"(1024,)","(1024,)"
blocks.4.mlp.w2.weight,NaN,"(1024, 384)","(1024, 384)"
blocks.4.mlp.w2.bias,NaN,"(1024,)","(1024,)"
blocks.4.mlp.w3.weight,NaN,"(384, 1024)","(384, 1024)"
blocks.4.mlp.w3.bias,NaN,"(384,)","(384,)"
blocks.5.mlp.w1.weight,NaN,"(1024, 384)","(1024, 384)"
blocks.5.mlp.w1.bias,NaN,"(1024,)","(1024,)"
blocks.5.mlp.w2.weight,NaN,"(1024, 384)","(1024, 384)"
blocks.5.mlp.w2.bias,NaN,"(1024,)","(1024,)"
blocks.5.mlp.w3.weight,NaN,"(384, 1024)","(384, 1024)"
blocks.5.mlp.w3.bias,NaN,"(384,)","(384,)"
blocks.6.mlp.w1.weight,NaN,"(1024, 384)","(1024, 384)"
blocks.6.mlp.w1.bias,NaN,"(1024,)","(1024,)"
blocks.6.mlp.w2.weight,NaN,"(1024, 384)","(1024, 384)"
blocks.6.mlp.w2.bias,NaN,"(1024,)","(1024,)"
blocks.6.mlp.w3.weight,NaN,"(384, 1024)","(384, 1024)"
blocks.6.mlp.w3.bias,NaN,"(384,)","(384,)"
blocks.7.mlp.w1.weight,NaN,"(1024, 384)","(1024, 384)"
blocks.7.mlp.w1.bias,NaN,"(1024,)","(1024,)"
blocks.7.mlp.w2.weight,NaN,"(1024, 384)","(1024, 384)"
blocks.7.mlp.w2.bias,NaN,"(1024,)","(1024,)"
blocks.7.mlp.w3.weight,NaN,"(384, 1024)","(384, 1024)"
blocks.7.mlp.w3.bias,NaN,"(384,)","(384,)"
blocks.8.mlp.w1.weight,NaN,"(1024, 384)","(1024, 384)"
blocks.8.mlp.w1.bias,NaN,"(1024,)","(1024,)"
blocks.8.mlp.w2.weight,NaN,"(1024, 384)","(1024, 384)"
blocks.8.mlp.w2.bias,NaN,"(1024,)","(1024,)"
blocks.8.mlp.w3.weight,NaN,"(384, 1024)","(384, 1024)"
blocks.8.mlp.w3.bias,NaN,"(384,)","(384,)"
blocks.9.mlp.w1.weight,NaN,"(1024, 384)","(1024, 384)"
blocks.9.mlp.w1.bias,NaN,"(1024,)","(1024,)"
blocks.9.mlp.w2.weight,NaN,"(1024, 384)","(1024, 384)"
blocks.9.mlp.w2.bias,NaN,"(1024,)","(1024,)"
blocks.9.mlp.w3.weight,NaN,"(384, 1024)","(384, 1024)"
blocks.9.mlp.w3.bias,NaN,"(384,)","(384,)"
blocks.10.mlp.w1.weight,NaN,"(1024, 384)","(1024, 384)"
blocks.10.mlp.w1.bias,NaN,"(1024,)","(1024,)"
blocks.10.mlp.w2.weight,NaN,"(1024, 384)","(1024, 384)"
blocks.10.mlp.w2.bias,NaN,"(1024,)","(1024,)"
blocks.10.mlp.w3.weight,NaN,"(384, 1024)","(384, 1024)"
blocks.10.mlp.w3.bias,NaN,"(384,)","(384,)"
blocks.11.mlp.w1.weight,NaN,"(1024, 384)","(1024, 384)"
blocks.11.mlp.w1.bias,NaN,"(1024,)","(1024,)"
blocks.11.mlp.w2.weight,NaN,"(1024, 384)","(1024, 384)"
blocks.11.mlp.w2.bias,NaN,"(1024,)","(1024,)"
blocks.11.mlp.w3.weight,NaN,"(384, 1024)","(384, 1024)"
blocks.11.mlp.w3.bias,NaN,"(384,)","(384,)"
local_cls_norm.weight,NaN,"(384,)","(384,)"
local_cls_norm.bias,NaN,"(384,)","(384,)"